### ISSUE TITLE
[BUG] NSC Path

### ISSUE THREAD

**Issue by AngeloBestetti** [qaze-dev/issues#3]
**Describe the bug**
Trying to set NSC.EXE path but it´s not working, typing or using "browse" to select the folder nothing happens

**To Reproduce**
1. Go to Application Settings
2. Click on Tool Paths
3. Click on Browse
4. Select the nsc.exe folder resides

**Expected behavior**
Expected NSC Path field be populated with the path selected, but goes back clear

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Qaze Version: Qaze Desktop v1.0.3

**Comment by sebholstein** [comment]
fixed with v1.0.4
